server:
  port: 8082
spring:
  redis:
    host: 127.0.0.1
    password:
easy:
  generator:
    client:
      generator-model: server
      redis-lock-key: id:generator:lock
      redis-lock-time: 5000
      id-list-redis-key: id:generator:list
      id-list-default-size: 100
      id-list-min-size: 50
      id-list-increase-number: 50
